### PR TITLE
[RHCLOUD-19765] Tekton endpoint skeleton

### PR DESCRIPTION
**Pull request by justinorringer**
### Changes
* Added Tekton endpoint setup and metrics
  * All it does now is log the request body.

[RHCLOUD-19765](https://issues.redhat.com/browse/RHCLOUD-19765)

### CODE REVIEW

**Review by CodyWMitchell — APPROVED** [review]
LGTM

**Review by dehort — APPROVED** [review]
Looks good to me!

If you have time, it might be good to add some automated unit tests.

**Comment by justinorringer** [comment]
Got some more stuff done on it thanks to Derek!

- Added ginkgo package for testing
- Simple test around the tekton enpoint using the mockdbconnector and ginkgo
- Moved the health endpoint and openapi to the endpoints folder
- Made openAPI spec path configurable

**Review by dehort — APPROVED** [review]
LGTM!

**Pull request merged**
